version: '3'

services:

  mysql:
    image: mysql:8.0
    container_name: todolist_mysql
    environment:
      MYSQL_DATABASE: 'todos'
      MYSQL_ROOT_PASSWORD: 'PASSWORD'
    networks: 
    - network
    ports:
    - "3307:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "-pPASSWORD", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  nodejs-expressjs:
    container_name: todolist_nodejs_expressjs
    build:
      context: .
      dockerfile: Dockerfile.web
    image: todolist-nodejs-expressjs
    networks: 
    - network
    ports:
      - "3000:3000"
    command: npm run dev

networks:
  network: