version: '3'

services:

  backend-api:
    container_name: avatares_backend
    build:
      context: .
      dockerfile: Dockerfile.api
    image: avatares-backend-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
    command: flask run --host=0.0.0.0 --port=5000

  frontend-web:
    container_name: avatares_frontend
    build:
      context: .
      dockerfile: Dockerfile.web
    image: avatares-frontend-web
    ports:
      - "5173:5173"
    environment:
      - VITE_HOST=${VITE_HOST}
      - VITE_PORT=${VITE_PORT}
    command: npm run dev