apiVersion: v1
kind: Service
metadata:
  name: avatares
spec:
  selector:
    app: avatares
  ports:
    - name: backend-api
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: frontend-web
      protocol: TCP
      port: 5173
      targetPort: 5173
  type: LoadBalancer
